export const ErrorCode = Object.freeze({
  AUTH_INVALID_USERNAME_OR_PASSWORD: "AUTH_INVALID_USERNAME_OR_PASSWORD",
  AUTH_ACCOUNT_IS_LOCKED_OUT: "AUTH_ACCOUNT_IS_LOCKED_OUT",
  AUTH_EMAIL_NOT_CONFIRMED: "AUTH_EMAIL_NOT_CONFIRMED",
  AUTH_INVALID_REFRESH_TOKEN: "AUTH_INVALID_REFRESH_TOKEN",
  AUTH_PASSWORD_RESET_FAILD: "AUTH_PASSWORD_RESET_FAILD",
  AUTH_PASSWORD_CHANGE_FAILD: "AUTH_PASSWORD_CHANGE_FAILD",

  BID_NOT_ALLOWED: "BID_NOT_ALLOWED",
  BID_AMOUNT_INVALID: "BID_AMOUNT_INVALID",
  AUCTION_ENDED: "AUCTION_ENDED",

  REVIEW_ALREADY_EXISTS: "REVIEW_ALREADY_EXISTS",

  PERMISSION_DENIED: "PERMISSION_DENIED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  UPLOADED_FILE_INVALID: "UPLOADED_FILE_INVALID",
  USER_INPUT_INVALID: "USER_INPUT_INVALID",
  SERVER_INTENRAL_ERROR: "SERVER_INTENRAL_ERROR",
});
