services:
  webapi:
    build: 
      context: . # To allow the Dockerfile to access all solution files (When we use COPY commands in the Dockerfile, paths are relative to this context)
      dockerfile: src/BidX.Presentation/Dockerfile
    image: bidx/webapi:latest
    container_name: webapi
    env_file: webapi.env
    ports:
      - 5000:8080
    depends_on:
      - mysql
    volumes:
      - webapi-logs:/app/Logs
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
    
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file: mysql.env
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  webapi-logs:
  mysql-data:
  dataprotection-keys: # For DataProtection keys otherwise I will got a warning that the keys will be unavailable when the container is destroyed see:https://andrewlock.net/an-introduction-to-the-data-protection-system-in-asp-net-core
